server:
  port: 8088

spring:
  datasource:
    url: jdbc:sqlserver://192.168.57.201:9981;database=PWC_DB;encrypt=true;trustServerCertificate=true
    username: pwc
    password: IISI@pwcdb
  profiles:
    active: '@spring.profiles.active@'
app:
  jwt:
    jwtSecret: jwtSecretKey
    #jwtExpiration: 86400000
    jwtExpiration: 86400000 #單位是ms ex 10000 就是10秒,這邊設定1天
  cors:
    allowed-origins: ''
