server:
  port: 7070
spring:
  datasource:
    url: jdbc:sqlserver://10.100.216.11:1433;SelectMethod=cursor;databaseName=PWC_DB;encrypt=true;trustServerCertificate=true
    username: pwc
    password: IISI@pwcdb