spring:
  datasource:
    url: jdbc:sqlserver://192.168.57.202:9977;database=PWC_DB;encrypt=true;trustServerCertificate=true
    username: pwc
    password: IISI@pwcdb

app:
  cors:
    allowed-origins: 'http://localhost:9000,http://localhost:9060'