server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlserver://10.100.15.32;SelectMethod=cursor;databaseName=PWC_DB;encrypt=true;trustServerCertificate=true
    username: pwc
    password: IISI@pwcdb