----- step1 back up tables
select * into ADM_CONTACT_BK from ADM_CONTACT
select * into BID_CPAMI_ARCHITECT_RESUME_BK from BID_CPAMI_ARCHITECT_RESUME
select * into BID_CPAMI_FTENG_BK from BID_CPAMI_FTENG
select * into BID_CPAMI_FTENG_RESUME_BK from BID_CPAMI_FTENG_RESUME
select * into BID_GOV_CHECKERR_BK from BID_GOV_CHECKERR
select * into BID_PE_BK from BID_PE
select * into BID_PRJ_PE_BK from BID_PRJ_PE
select * into BID_PERSONNEL_RESUME_BK from BID_PERSONNEL_RESUME
select * into BID_PERSONNEL_RESUME_ITEM_BK from BID_PERSONNEL_RESUME_ITEM
select * into BID_PISPBAS_BK from BID_PISPBAS
select * into BID_PISP_BASEDATA_BK from BID_PISP_BASEDATA
select * into BID_PISP_DATE_EXTEND_BK from BID_PISP_DATE_EXTEND
select * into BID_PRJ_QC_BK from BID_PRJ_QC
select * into BID_PRJ_WKMENG_BK from BID_PRJ_WKMENG
select * into BID_QC_RETRAIN_BK from BID_QC_RETRAIN
select * into BID_QC_TRAIN_BK from BID_QC_TRAIN
select * into ENG_CHECK_BK from ENG_CHECK
select * into ENG_COMP_MEMBER_BK from ENG_COMP_MEMBER
select * into ENG_CST_LICENSE_BK from ENG_CST_LICENSE
select * into ENG_CST_LICENSE_MEMBER_BK from ENG_CST_LICENSE_MEMBER
select * into ENG_ENGRCLASS_RECORD_BK from ENG_ENGRCLASS_RECORD
select * into ENG_ENGRCLASS_RECORD_DETAIL_BK from ENG_ENGRCLASS_RECORD_DETAIL
select * into ENG_ENGR_CERTIFICATE_BK from ENG_ENGR_CERTIFICATE
select * into ENG_ENGR_DISCIPLINE_BK from ENG_ENGR_DISCIPLINE
select * into ENG_ENGR_EXAM_BK from ENG_ENGR_EXAM
select * into ENG_ENGR_INSURANCE_BK from ENG_ENGR_INSURANCE
select * into ENG_ENGR_LICENSE_BK from ENG_ENGR_LICENSE
select * into ENG_MEMBER_BK from ENG_MEMBER
select * into ENG_YEARREPORT_BK from ENG_YEARREPORT
select * into ENG_YEARREPORT_CASE_ENGR_BK from ENG_YEARREPORT_CASE_ENGR
select * into ENG_YEARREPORT_ENGR_BK from ENG_YEARREPORT_ENGR
select * into ENG_YEARREPORT_IMPORT_LOG_BK from ENG_YEARREPORT_IMPORT_LOG
select * into ECT_PUBLIC_BK from ECT_PUBLIC
select * into ECT_CHECK_BK from ECT_CHECK
select * into GEO_EXAM_PASS_IMPORT_BK from GEO_EXAM_PASS_IMPORT
select * into GEO_MEMBER_BK from GEO_MEMBER
select * into QUA_QTRAIN_PERSON_BK from QUA_QTRAIN_PERSON
select * into QUA_QTRAIN_QUESTIONNAIRE_BK from QUA_QTRAIN_QUESTIONNAIRE
select * into QUA_QTRAIN_STUDENT_BK from QUA_QTRAIN_STUDENT
----- step2 add column
ALTER TABLE dbo.ADM_CONTACT 
ADD IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_CPAMI_ARCHITECT_RESUME 
ADD IDN_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_CPAMI_FTENG 
ADD FTENG_IDN_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_CPAMI_FTENG_RESUME 
ADD IDN_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_GOV_CHECKERR 
ADD ROVE_TO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_PE 
ADD ID_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_PRJ_PE 
ADD ID_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_PERSONNEL_RESUME 
ADD IDN_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_PERSONNEL_RESUME_ITEM 
ADD IDN_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_PISPBAS 
ADD P_ID_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_PISP_BASEDATA 
ADD P_ID_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_PISP_DATE_EXTEND 
ADD P_ID_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_PRJ_QC 
ADD ID_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_PRJ_WKMENG 
ADD ID_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_QC_RETRAIN 
ADD ID_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.BID_QC_TRAIN 
ADD ID_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_CHECK 
ADD ENGR_IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_COMP_MEMBER 
ADD MEMBER_IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_CST_LICENSE 
ADD MASTER_IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_CST_LICENSE_MEMBER 
ADD MEMBER_IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_ENGRCLASS_RECORD 
ADD IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_ENGRCLASS_RECORD_DETAIL 
ADD IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_ENGR_CERTIFICATE 
ADD IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_ENGR_DISCIPLINE 
ADD ENGR_IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_ENGR_EXAM 
ADD IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_ENGR_INSURANCE 
ADD IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_ENGR_LICENSE 
ADD IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_MEMBER 
ADD IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_YEARREPORT 
ADD ENGR_IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_YEARREPORT_CASE_ENGR 
ADD IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_YEARREPORT_ENGR 
ADD ENGR_IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ENG_YEARREPORT_IMPORT_LOG 
ADD IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ECT_PUBLIC 
ADD IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.ECT_CHECK 
ADD IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.GEO_EXAM_PASS_IMPORT 
ADD IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.GEO_MEMBER 
ADD IDNO_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.QUA_QTRAIN_PERSON 
ADD PEO_ID_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.QUA_QTRAIN_QUESTIONNAIRE 
ADD PEO_ID_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
ALTER TABLE dbo.QUA_QTRAIN_STUDENT 
ADD PEO_ID_ENCRYPT 
varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256')
----- step3 copy data by api with following request
{
 "tableName":"ADM_CONTACT",
 "originColName":"IDNO",
 "encryptColName":"IDNO_ENCRYPT",
 "pkColName":"USER_ID" 
},
{
 "tableName":"BID_CPAMI_ARCHITECT_RESUME",
 "originColName":"IDN",
 "encryptColName":"IDN_ENCRYPT",
 "pkColName":"IDN" 
},
{
 "tableName":"BID_CPAMI_FTENG",
 "originColName":"FTENG_IDN",
 "encryptColName":"FTENG_IDN_ENCRYPT",
 "pkColName":"FTENG_IDN,CPAMI_KEY" 
},
{
 "tableName":"BID_CPAMI_FTENG_RESUME",
 "originColName":"IDN",
 "encryptColName":"IDN_ENCRYPT",
 "pkColName":"IDN,JOB_TITLE,START_DATE" 
},
{
 "tableName":"BID_GOV_CHECKERR",
 "originColName":"ROVE_TO",
 "encryptColName":"ROVE_TO_ENCRYPT",
 "pkColName":"WKUT,PRJNO,CHECK_DATE,ERR_NUM" 
},
{
 "tableName":"BID_PE",
 "originColName":"ID",
 "encryptColName":"ID_ENCRYPT",
 "pkColName":"ID" 
},
{
 "tableName":"BID_PRJ_PE",
 "originColName":"ID",
 "encryptColName":"ID_ENCRYPT",
 "pkColName":"WKUT,PRJNO,ID,PNAME,START_DATE,JOB_TYPE" 
},
{
 "tableName":"BID_PERSONNEL_RESUME",
 "originColName":"IDN",
 "encryptColName":"IDN_ENCRYPT",
 "pkColName":"IDN,JOB_TITLE" 
},
{
 "tableName":"BID_PERSONNEL_RESUME_ITEM",
 "originColName":"IDN",
 "encryptColName":"IDN_ENCRYPT",
 "pkColName":"IDN,JOB_TITLE,INTERVAL_NO,WKUT,PRJNO" 
},
{
 "tableName":"BID_PISPBAS",
 "originColName":"P_ID",
 "encryptColName":"P_ID_ENCRYPT",
 "pkColName":"WKUT,P_ID,PK1" 
},
{
 "tableName":"BID_PISP_BASEDATA",
 "originColName":"P_ID",
 "encryptColName":"P_ID_ENCRYPT",
 "pkColName":"P_ID" 
},
{
 "tableName":"BID_PISP_DATE_EXTEND",
 "originColName":"P_ID",
 "encryptColName":"P_ID_ENCRYPT",
 "pkColName":"CHECK_UNIT,SDATE,P_ID" 
},
{
 "tableName":"BID_PRJ_QC",
 "originColName":"ID",
 "encryptColName":"ID_ENCRYPT",
 "pkColName":"WKUT,PRJNO,ID,START_DATE,JOB_TYPE" 
},
{
 "tableName":"BID_PRJ_WKMENG",
 "originColName":"ID",
 "encryptColName":"ID_ENCRYPT",
 "pkColName":"WKUT,PRJNO,ID,JOB,START_DATE" 
},
{
 "tableName":"BID_QC_RETRAIN",
 "originColName":"ID",
 "encryptColName":"ID_ENCRYPT",
 "pkColName":"ID,CLASS2" 
},
{
 "tableName":"BID_QC_TRAIN",
 "originColName":"ID",
 "encryptColName":"ID_ENCRYPT",
 "pkColName":"ID,QC_TYPE" 
},
{
 "tableName":"ENG_CHECK",
 "originColName":"ENGR_IDNO",
 "encryptColName":"ENGR_IDNO_ENCRYPT",
 "pkColName":"ENG_CHECK_ID" 
},
{
 "tableName":"ENG_COMP_MEMBER",
 "originColName":"MEMBER_IDNO",
 "encryptColName":"MEMBER_IDNO_ENCRYPT",
 "pkColName":"ENG_COMP_ID,ENG_COMP_MEMBER_ID,ENG_COMP_MEMBER_TYPE" 
},
{
 "tableName":"ENG_CST_LICENSE",
 "originColName":"MASTER_IDNO",
 "encryptColName":"MASTER_IDNO_ENCRYPT",
 "pkColName":"ENG_CST_LICENSE_ID,ENG_CST_LICENSE_VERSION" 
},
{
 "tableName":"ENG_CST_LICENSE_MEMBER",
 "originColName":"MEMBER_IDNO",
 "encryptColName":"MEMBER_IDNO_ENCRYPT",
 "pkColName":"ENG_CST_LICENSE_ID,ENG_CST_LICENSE_MEMBER_ID,ENG_CST_LICENSE_VERSION" 
},
{
 "tableName":"ENG_ENGRCLASS_RECORD",
 "originColName":"IDNO",
 "encryptColName":"IDNO_ENCRYPT",
 "pkColName":"ENG_ENGRCLASS_RECORD_ID" 
},
{
 "tableName":"ENG_ENGRCLASS_RECORD_DETAIL",
 "originColName":"IDNO",
 "encryptColName":"IDNO_ENCRYPT",
 "pkColName":"ENG_COURSE_DETAIL_ID,ENG_ENGRCLASS_RECORD_ID" 
},
{
 "tableName":"ENG_ENGR_CERTIFICATE",
 "originColName":"IDNO",
 "encryptColName":"IDNO_ENCRYPT",
 "pkColName":"ENG_ENGR_CERTIFICATE_ID,ENG_ENGR_CERTIFICATE_VERSION" 
},
{
 "tableName":"ENG_ENGR_DISCIPLINE",
 "originColName":"ENGR_IDNO",
 "encryptColName":"ENGR_IDNO_ENCRYPT",
 "pkColName":"ENG_ENGR_DISCIPLINE_ID" 
},
{
 "tableName":"ENG_ENGR_EXAM",
 "originColName":"IDNO",
 "encryptColName":"IDNO_ENCRYPT",
 "pkColName":"ENG_ENGR_EXAM_ID" 
},
{
 "tableName":"ENG_ENGR_INSURANCE",
 "originColName":"IDNO",
 "encryptColName":"IDNO_ENCRYPT",
 "pkColName":"ENG_ENGR_INSURANCE_ID" 
},
{
 "tableName":"ENG_ENGR_LICENSE",
 "originColName":"IDNO",
 "encryptColName":"IDNO_ENCRYPT",
 "pkColName":"ENG_ENGR_LICENSE_ID,ENG_ENGR_LICENSE_VERSION" 
},
{
 "tableName":"ENG_MEMBER",
 "originColName":"IDNO",
 "encryptColName":"IDNO_ENCRYPT",
 "pkColName":"ENG_MEMBER_ID" 
},
{
 "tableName":"ENG_YEARREPORT",
 "originColName":"ENGR_IDNO",
 "encryptColName":"ENGR_IDNO_ENCRYPT",
 "pkColName":"ENG_YEARREPORT_ID,ENG_YEARREPORT_YYYY" 
},
{
 "tableName":"ENG_YEARREPORT_CASE_ENGR",
 "originColName":"IDNO",
 "encryptColName":"IDNO_ENCRYPT",
 "pkColName":"ENG_YEARREPORT_CASE_ENGR_ID,ENG_YEARREPORT_CASE_GUID,ENG_YEARREPORT_CASE_ID,ENG_YEARREPORT_ID,ENG_YEARREPORT_YYYY" 
},
{
 "tableName":"ENG_YEARREPORT_ENGR",
 "originColName":"ENGR_IDNO",
 "encryptColName":"ENGR_IDNO_ENCRYPT",
 "pkColName":"ENG_YEARREPORT_ENGR_ID,ENG_YEARREPORT_ID,ENG_YEARREPORT_YYYY" 
},
{
 "tableName":"ENG_YEARREPORT_IMPORT_LOG",
 "originColName":"IDNO",
 "encryptColName":"IDNO_ENCRYPT",
 "pkColName":"ENG_YEARREPORT_IMPORT_LOG_ID" 
},
{
 "tableName":"ECT_PUBLIC",
 "originColName":"IDNO",
 "encryptColName":"IDNO_ENCRYPT",
 "pkColName":"ECT_PUBLISH_ID" 
},
{
 "tableName":"ECT_CHECK",
 "originColName":"IDNO",
 "encryptColName":"IDNO_ENCRYPT",
 "pkColName":"ECT_CHECK_ID" 
},
{
 "tableName":"GEO_EXAM_PASS_IMPORT",
 "originColName":"IDNO",
 "encryptColName":"IDNO_ENCRYPT",
 "pkColName":"GEO_EXAM_PASS_IMPORT_ID" 
},
{
 "tableName":"GEO_MEMBER",
 "originColName":"IDNO",
 "encryptColName":"IDNO_ENCRYPT",
 "pkColName":"GEO_MEMBER_ID" 
},
{
 "tableName":"QUA_QTRAIN_PERSON",
 "originColName":"PEO_ID",
 "encryptColName":"PEO_ID_ENCRYPT",
 "pkColName":"SID" 
},
{
 "tableName":"QUA_QTRAIN_QUESTIONNAIRE",
 "originColName":"PEO_ID",
 "encryptColName":"PEO_ID_ENCRYPT",
 "pkColName":"QUA_QTRAIN_QUESTIONNAIRE_ID" 
},
{
 "tableName":"QUA_QTRAIN_STUDENT",
 "originColName":"PEO_ID",
 "encryptColName":"PEO_ID_ENCRYPT",
 "pkColName":"QUA_QTRAIN_STUDENT_ID" 
},
----- step4 rename columns
EXEC sp_rename 'dbo.ADM_CONTACT.IDNO', 'IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_CPAMI_ARCHITECT_RESUME.IDN', 'IDN_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_CPAMI_FTENG.FTENG_IDN', 'FTENG_IDN_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_CPAMI_FTENG_RESUME.IDN', 'IDN_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_GOV_CHECKERR.ROVE_TO', 'ROVE_TO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_PE.ID', 'ID_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_PRJ_PE.ID', 'ID_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_PERSONNEL_RESUME.IDN', 'IDN_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_PERSONNEL_RESUME_ITEM.IDN', 'IDN_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_PISPBAS.P_ID', 'P_ID_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_PISP_BASEDATA.P_ID', 'P_ID_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_PISP_DATE_EXTEND.P_ID', 'P_ID_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_PRJ_QC.ID', 'ID_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_PRJ_WKMENG.ID', 'ID_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_QC_RETRAIN.ID', 'ID_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.BID_QC_TRAIN.ID', 'ID_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_CHECK.ENGR_IDNO', 'ENGR_IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_COMP_MEMBER.MEMBER_IDNO', 'MEMBER_IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_CST_LICENSE.MASTER_IDNO', 'MASTER_IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_CST_LICENSE_MEMBER.MEMBER_IDNO', 'MEMBER_IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_ENGRCLASS_RECORD.IDNO', 'IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_ENGRCLASS_RECORD_DETAIL.IDNO', 'IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_ENGR_CERTIFICATE.IDNO', 'IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_ENGR_DISCIPLINE.ENGR_IDNO', 'ENGR_IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_ENGR_EXAM.IDNO', 'IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_ENGR_INSURANCE.IDNO', 'IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_ENGR_LICENSE.IDNO', 'IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_MEMBER.IDNO', 'IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_YEARREPORT.ENGR_IDNO', 'ENGR_IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_YEARREPORT_CASE_ENGR.IDNO', 'IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_YEARREPORT_ENGR.ENGR_IDNO', 'ENGR_IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ENG_YEARREPORT_IMPORT_LOG.IDNO', 'IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ECT_PUBLIC.IDNO', 'IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.ECT_CHECK.IDNO', 'IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.GEO_EXAM_PASS_IMPORT.IDNO', 'IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.GEO_MEMBER.IDNO', 'IDNO_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.QUA_QTRAIN_PERSON.PEO_ID', 'PEO_ID_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.QUA_QTRAIN_QUESTIONNAIRE.PEO_ID', 'PEO_ID_DECRYPT', 'COLUMN';
EXEC sp_rename 'dbo.QUA_QTRAIN_STUDENT.PEO_ID', 'PEO_ID_DECRYPT', 'COLUMN';

EXEC sp_rename 'dbo.ADM_CONTACT.IDNO_ENCRYPT', 'IDNO', 'COLUMN';
EXEC sp_rename 'dbo.BID_CPAMI_ARCHITECT_RESUME.IDN_ENCRYPT', 'IDN', 'COLUMN';
EXEC sp_rename 'dbo.BID_CPAMI_FTENG.FTENG_IDN_ENCRYPT', 'FTENG_IDN', 'COLUMN';
EXEC sp_rename 'dbo.BID_CPAMI_FTENG_RESUME.IDN_ENCRYPT', 'IDN', 'COLUMN';
EXEC sp_rename 'dbo.BID_GOV_CHECKERR.ROVE_TO_ENCRYPT', 'ROVE_TO', 'COLUMN';
EXEC sp_rename 'dbo.BID_PE.ID_ENCRYPT', 'ID', 'COLUMN';
EXEC sp_rename 'dbo.BID_PRJ_PE.ID_ENCRYPT', 'ID', 'COLUMN';
EXEC sp_rename 'dbo.BID_PERSONNEL_RESUME.IDN_ENCRYPT', 'IDN', 'COLUMN';
EXEC sp_rename 'dbo.BID_PERSONNEL_RESUME_ITEM.IDN_ENCRYPT', 'IDN', 'COLUMN';
EXEC sp_rename 'dbo.BID_PISPBAS.P_ID_ENCRYPT', 'P_ID', 'COLUMN';
EXEC sp_rename 'dbo.BID_PISP_BASEDATA.P_ID_ENCRYPT', 'P_ID', 'COLUMN';
EXEC sp_rename 'dbo.BID_PISP_DATE_EXTEND.P_ID_ENCRYPT', 'P_ID', 'COLUMN';
EXEC sp_rename 'dbo.BID_PRJ_QC.ID_ENCRYPT', 'ID', 'COLUMN';
EXEC sp_rename 'dbo.BID_PRJ_WKMENG.ID_ENCRYPT', 'ID', 'COLUMN';
EXEC sp_rename 'dbo.BID_QC_RETRAIN.ID_ENCRYPT', 'ID', 'COLUMN';
EXEC sp_rename 'dbo.BID_QC_TRAIN.ID_ENCRYPT', 'ID', 'COLUMN';
EXEC sp_rename 'dbo.ENG_CHECK.ENGR_IDNO_ENCRYPT', 'ENGR_IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_COMP_MEMBER.MEMBER_IDNO_ENCRYPT', 'MEMBER_IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_CST_LICENSE.MASTER_IDNO_ENCRYPT', 'MASTER_IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_CST_LICENSE_MEMBER.MEMBER_IDNO_ENCRYPT', 'MEMBER_IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_ENGRCLASS_RECORD.IDNO_ENCRYPT', 'IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_ENGRCLASS_RECORD_DETAIL.IDNO_ENCRYPT', 'IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_ENGR_CERTIFICATE.IDNO_ENCRYPT', 'IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_ENGR_DISCIPLINE.ENGR_IDNO_ENCRYPT', 'ENGR_IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_ENGR_EXAM.IDNO_ENCRYPT', 'IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_ENGR_INSURANCE.IDNO_ENCRYPT', 'IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_ENGR_LICENSE.IDNO_ENCRYPT', 'IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_MEMBER.IDNO_ENCRYPT', 'IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_YEARREPORT.ENGR_IDNO_ENCRYPT', 'ENGR_IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_YEARREPORT_CASE_ENGR.IDNO_ENCRYPT', 'IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_YEARREPORT_ENGR.ENGR_IDNO_ENCRYPT', 'ENGR_IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ENG_YEARREPORT_IMPORT_LOG.IDNO_ENCRYPT', 'IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ECT_PUBLIC.IDNO_ENCRYPT', 'IDNO', 'COLUMN';
EXEC sp_rename 'dbo.ECT_CHECK.IDNO_ENCRYPT', 'IDNO', 'COLUMN';
EXEC sp_rename 'dbo.GEO_EXAM_PASS_IMPORT.IDNO_ENCRYPT', 'IDNO', 'COLUMN';
EXEC sp_rename 'dbo.GEO_MEMBER.IDNO_ENCRYPT', 'IDNO', 'COLUMN';
EXEC sp_rename 'dbo.QUA_QTRAIN_PERSON.PEO_ID_ENCRYPT', 'PEO_ID', 'COLUMN';
EXEC sp_rename 'dbo.QUA_QTRAIN_QUESTIONNAIRE.PEO_ID_ENCRYPT', 'PEO_ID', 'COLUMN';
EXEC sp_rename 'dbo.QUA_QTRAIN_STUDENT.PEO_ID_ENCRYPT', 'PEO_ID', 'COLUMN';
----- step5 handle pk
ALTER TABLE BID_CPAMI_ARCHITECT_RESUME DROP CONSTRAINT PK_BID_CPAMI_ARCHITECT_RESUME;
                
ALTER TABLE BID_CPAMI_ARCHITECT_RESUME ALTER COLUMN IDN varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL;
                
ALTER TABLE BID_CPAMI_ARCHITECT_RESUME ALTER COLUMN IDN_DECRYPT varchar(200) NULL;
                
ALTER TABLE BID_CPAMI_ARCHITECT_RESUME ADD CONSTRAINT PK_BID_CPAMI_ARCHITECT_RESUME PRIMARY KEY (IDN,BUSINESS_NO);
            
ALTER TABLE BID_CPAMI_FTENG DROP CONSTRAINT PK_BID_CPAMI_FTENG;
                
ALTER TABLE BID_CPAMI_FTENG ALTER COLUMN FTENG_IDN varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL;
                
ALTER TABLE BID_CPAMI_FTENG ALTER COLUMN FTENG_IDN_DECRYPT varchar(200) NULL;
                
ALTER TABLE BID_CPAMI_FTENG ADD CONSTRAINT PK_BID_CPAMI_FTENG PRIMARY KEY (FTENG_IDN,CPAMI_KEY);
            
ALTER TABLE BID_CPAMI_FTENG_RESUME DROP CONSTRAINT PK_BID_CPAMI_FTENG_RESUME;
                
ALTER TABLE BID_CPAMI_FTENG_RESUME ALTER COLUMN IDN varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL;
                
ALTER TABLE BID_CPAMI_FTENG_RESUME ALTER COLUMN IDN_DECRYPT varchar(200) NULL;
                
ALTER TABLE BID_CPAMI_FTENG_RESUME ADD CONSTRAINT PK_BID_CPAMI_FTENG_RESUME PRIMARY KEY (IDN,JOB_TITLE,START_DATE);
            
ALTER TABLE BID_PE DROP CONSTRAINT PK_BID_PE;
                
ALTER TABLE BID_PE ALTER COLUMN ID varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL;
                
ALTER TABLE BID_PE ALTER COLUMN ID_DECRYPT varchar(200) NULL;
                
ALTER TABLE BID_PE ADD CONSTRAINT PK_BID_PE PRIMARY KEY (ID);
            
ALTER TABLE BID_PRJ_PE DROP CONSTRAINT PK_BID_PRJ_PE;
                
ALTER TABLE BID_PRJ_PE ALTER COLUMN ID varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL;
                
ALTER TABLE BID_PRJ_PE ALTER COLUMN ID_DECRYPT varchar(200) NULL;
                
ALTER TABLE BID_PRJ_PE ADD CONSTRAINT PK_BID_PRJ_PE PRIMARY KEY (WKUT,PRJNO,ID,PNAME,START_DATE,JOB_TYPE);
            
ALTER TABLE BID_PERSONNEL_RESUME DROP CONSTRAINT PK_BID_PERSONNEL_RESUME;
                
ALTER TABLE BID_PERSONNEL_RESUME ALTER COLUMN IDN varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL;
                
ALTER TABLE BID_PERSONNEL_RESUME ALTER COLUMN IDN_DECRYPT varchar(200) NULL;
                
ALTER TABLE BID_PERSONNEL_RESUME ADD CONSTRAINT PK_BID_PERSONNEL_RESUME PRIMARY KEY (IDN,NAME,JOB_TITLE);
            
ALTER TABLE BID_PERSONNEL_RESUME_ITEM DROP CONSTRAINT PK_BID_PERSONNEL_RESUME_ITEM;
                
ALTER TABLE BID_PERSONNEL_RESUME_ITEM ALTER COLUMN IDN varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL;
                
ALTER TABLE BID_PERSONNEL_RESUME_ITEM ALTER COLUMN IDN_DECRYPT varchar(200) NULL;
                
ALTER TABLE BID_PERSONNEL_RESUME_ITEM ADD CONSTRAINT PK_BID_PERSONNEL_RESUME_ITEM PRIMARY KEY (IDN,NAME,JOB_TITLE,INTERVAL_NO,WKUT,PRJNO);
            
ALTER TABLE BID_PISPBAS DROP CONSTRAINT PK_BID_PISPBAS;
                
ALTER TABLE BID_PISPBAS ALTER COLUMN P_ID varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL;
                
ALTER TABLE BID_PISPBAS ALTER COLUMN P_ID_DECRYPT varchar(200) NULL;
                
ALTER TABLE BID_PISPBAS ADD CONSTRAINT PK_BID_PISPBAS PRIMARY KEY (WKUT,P_ID,PK1);
            
ALTER TABLE BID_PISP_BASEDATA DROP CONSTRAINT PK_BID_PISP_BASEDATA;
                
ALTER TABLE BID_PISP_BASEDATA ALTER COLUMN P_ID varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL;
                
ALTER TABLE BID_PISP_BASEDATA ALTER COLUMN P_ID_DECRYPT varchar(200) NULL;
                
ALTER TABLE BID_PISP_BASEDATA ADD CONSTRAINT PK_BID_PISP_BASEDATA PRIMARY KEY (P_ID);
            
ALTER TABLE BID_PISP_DATE_EXTEND DROP CONSTRAINT PK_BID_PISP_DATE_EXTEND;
                
ALTER TABLE BID_PISP_DATE_EXTEND ALTER COLUMN P_ID varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL;
                
ALTER TABLE BID_PISP_DATE_EXTEND ALTER COLUMN P_ID_DECRYPT varchar(200) NULL;
                
ALTER TABLE BID_PISP_DATE_EXTEND ADD CONSTRAINT PK_BID_PISP_DATE_EXTEND PRIMARY KEY (CHECK_UNIT,SDATE,P_ID);
            
ALTER TABLE BID_PRJ_QC DROP CONSTRAINT PK_BID_PRJ_QC;
                
ALTER TABLE BID_PRJ_QC ALTER COLUMN ID varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL;
                
ALTER TABLE BID_PRJ_QC ALTER COLUMN ID_DECRYPT varchar(200) NULL;
                
ALTER TABLE BID_PRJ_QC ADD CONSTRAINT PK_BID_PRJ_QC PRIMARY KEY (WKUT,PRJNO,ID,START_DATE,JOB_TYPE);
            
ALTER TABLE BID_PRJ_WKMENG DROP CONSTRAINT PK_BID_PRJ_WKMENG;
                
ALTER TABLE BID_PRJ_WKMENG ALTER COLUMN ID varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL;
                
ALTER TABLE BID_PRJ_WKMENG ALTER COLUMN ID_DECRYPT varchar(200) NULL;
                
ALTER TABLE BID_PRJ_WKMENG ADD CONSTRAINT PK_BID_PRJ_WKMENG PRIMARY KEY (WKUT,PRJNO,ID,JOB,START_DATE);
            
ALTER TABLE BID_QC_RETRAIN DROP CONSTRAINT PK_BID_QC_RETRAIN;
                
ALTER TABLE BID_QC_RETRAIN ALTER COLUMN ID varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL;
                
ALTER TABLE BID_QC_RETRAIN ALTER COLUMN ID_DECRYPT varchar(200) NULL;
                
ALTER TABLE BID_QC_RETRAIN ADD CONSTRAINT PK_BID_QC_RETRAIN PRIMARY KEY (ID,CLASS2);
            
ALTER TABLE BID_QC_TRAIN DROP CONSTRAINT PK_BID_QC_TRAIN;
                
ALTER TABLE BID_QC_TRAIN ALTER COLUMN ID varchar(200) COLLATE Chinese_Taiwan_Stroke_BIN2  ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = JavaCEK, ENCRYPTION_TYPE = DETERMINISTIC, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL;
                
ALTER TABLE BID_QC_TRAIN ALTER COLUMN ID_DECRYPT varchar(200) NULL;
                
ALTER TABLE BID_QC_TRAIN ADD CONSTRAINT PK_BID_QC_TRAIN PRIMARY KEY (ID,QC_TYPE);
            
----- reverse step
select top 100 * from ADM_CONTACT where IDNO_DECRYPT is not null and IDNO is null
select top 100 * from BID_CPAMI_ARCHITECT_RESUME where IDN_DECRYPT is not null and IDN is null
select top 100 * from BID_CPAMI_FTENG where FTENG_IDN_DECRYPT is not null and FTENG_IDN is null
select top 100 * from BID_CPAMI_FTENG_RESUME where IDN_DECRYPT is not null and IDN is null
select top 100 * from BID_GOV_CHECKERR where ROVE_TO_DECRYPT is not null and ROVE_TO is null
select top 100 * from BID_PE where ID_DECRYPT is not null and ID is null
select top 100 * from BID_PRJ_PE where ID_DECRYPT is not null and ID is null
select top 100 * from BID_PERSONNEL_RESUME where IDN_DECRYPT is not null and IDN is null
select top 100 * from BID_PERSONNEL_RESUME_ITEM where IDN_DECRYPT is not null and IDN is null
select top 100 * from BID_PISPBAS where P_ID_DECRYPT is not null and P_ID is null
select top 100 * from BID_PISP_BASEDATA where P_ID_DECRYPT is not null and P_ID is null
select top 100 * from BID_PISP_DATE_EXTEND where P_ID_DECRYPT is not null and P_ID is null
select top 100 * from BID_PRJ_QC where ID_DECRYPT is not null and ID is null
select top 100 * from BID_PRJ_WKMENG where ID_DECRYPT is not null and ID is null
select top 100 * from BID_QC_RETRAIN where ID_DECRYPT is not null and ID is null
select top 100 * from BID_QC_TRAIN where ID_DECRYPT is not null and ID is null
select top 100 * from ENG_CHECK where ENGR_IDNO_DECRYPT is not null and ENGR_IDNO is null
select top 100 * from ENG_COMP_MEMBER where MEMBER_IDNO_DECRYPT is not null and MEMBER_IDNO is null
select top 100 * from ENG_CST_LICENSE where MASTER_IDNO_DECRYPT is not null and MASTER_IDNO is null
select top 100 * from ENG_CST_LICENSE_MEMBER where MEMBER_IDNO_DECRYPT is not null and MEMBER_IDNO is null
select top 100 * from ENG_ENGRCLASS_RECORD where IDNO_DECRYPT is not null and IDNO is null
select top 100 * from ENG_ENGRCLASS_RECORD_DETAIL where IDNO_DECRYPT is not null and IDNO is null
select top 100 * from ENG_ENGR_CERTIFICATE where IDNO_DECRYPT is not null and IDNO is null
select top 100 * from ENG_ENGR_DISCIPLINE where ENGR_IDNO_DECRYPT is not null and ENGR_IDNO is null
select top 100 * from ENG_ENGR_EXAM where IDNO_DECRYPT is not null and IDNO is null
select top 100 * from ENG_ENGR_INSURANCE where IDNO_DECRYPT is not null and IDNO is null
select top 100 * from ENG_ENGR_LICENSE where IDNO_DECRYPT is not null and IDNO is null
select top 100 * from ENG_MEMBER where IDNO_DECRYPT is not null and IDNO is null
select top 100 * from ENG_YEARREPORT where ENGR_IDNO_DECRYPT is not null and ENGR_IDNO is null
select top 100 * from ENG_YEARREPORT_CASE_ENGR where IDNO_DECRYPT is not null and IDNO is null
select top 100 * from ENG_YEARREPORT_ENGR where ENGR_IDNO_DECRYPT is not null and ENGR_IDNO is null
select top 100 * from ENG_YEARREPORT_IMPORT_LOG where IDNO_DECRYPT is not null and IDNO is null
select top 100 * from ECT_PUBLIC where IDNO_DECRYPT is not null and IDNO is null
select top 100 * from ECT_CHECK where IDNO_DECRYPT is not null and IDNO is null
select top 100 * from GEO_EXAM_PASS_IMPORT where IDNO_DECRYPT is not null and IDNO is null
select top 100 * from GEO_MEMBER where IDNO_DECRYPT is not null and IDNO is null
select top 100 * from QUA_QTRAIN_PERSON where PEO_ID_DECRYPT is not null and PEO_ID is null
select top 100 * from QUA_QTRAIN_QUESTIONNAIRE where PEO_ID_DECRYPT is not null and PEO_ID is null
select top 100 * from QUA_QTRAIN_STUDENT where PEO_ID_DECRYPT is not null and PEO_ID is null
